### ISSUE TITLE
MOCKUPS: checkbox styles

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening-ui-prototypes#21]
Going to play around with how we can restyle major checkboxes instead of using standard checkboxes, which don't allow for styling.

**Comment by mapsam** [comment]
Here are some first cracks, with the associated HTML and SASS - they all continue to rely on the `<input type="checkbox">`!

### Basic

<img width="722" alt="screen shot 2015-07-16 at 10 22 28 am" src="https://cloud.githubusercontent.com/assets/1943001/8730253/98ac7886-2ba4-11e5-8c59-1cbd06109d09.png">

``` HTML
<label class="field_checkbox example_1">
    <input type="checkbox" class="text" value="1" name="services" checked="true">
        Daily Planet
</label>
```

``` SCSS
&.example_1 {
  display: inline-block;
  padding: 1em;
  font-size: 1em;
  background-color: $color-lightgray;
}
```
